server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          proxy.https:
            host: localhost
            port: 7897
          proxy.http:
            host: localhost
            port: 7897
          uri: https://github.com/syh666666662/orderingsystem.git #git仓库地址
          searchPaths: config #仓库路径
          username: syh666666662 #git仓库用户名
          password: 23018120040724035X #git仓库密码
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/